version: '3'
services:
    rasa:
      container_name: "rasa_server"
      build: 
        context: backend
      ports: 
        - "5000:5000"
    action_server:
      container_name: "action_server"
      build: 
        context: actions
      volumes:
        - ./actions:/app/actions
      ports:
        - "5055:5055"  
